# -*- coding: utf-8 -*-
"""kmeans_llm_c_visu_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfEzaZZ9aIaKsfCq7AZYqGfqDnYAYq-Q

#### Código advindo de: https://towardsdatascience.com/mastering-customer-segmentation-with-llm-3d9008235f41#3a33

## Mastering Customer Segmentation with LLM

### TO-DO List:

<ul>
    <li> Sentence Embedding </li>
    <li> Create a Kmeans model</li>
    <li> Evaluate it</li>
</ul>

### Passo 1 - Importação
"""

import pandas as pd # dataframe manipulation
import numpy as np # linear algebra

# data visualization
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import plotly.express as px
import plotly.graph_objects as go

#import pyod
import pyod
import seaborn as sns
import shap

# sklearn
from sklearn.cluster import KMeans
from sklearn.preprocessing import PowerTransformer, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score, silhouette_samples, accuracy_score, classification_report

#from pyod.models.ecod import ECOD
from pyod.models.ecod import ECOD
from yellowbrick.cluster import KElbowVisualizer

#busca semantica
from sentence_transformers import SentenceTransformer, util

import lightgbm as lgb
import prince

from sentence_transformers import SentenceTransformer

"""### Passo 2 - Lendo e tratando o dataset"""
import chardet

# Detect encoding first
with open('all_ideas.CSV', 'rb') as f:
    result = chardet.detect(f.read(10000))  # Read first 10k bytes to guess

df = pd.read_csv("all_ideas.CSV", encoding=result['encoding'], delimiter=';')
# Text cleaning with proper regex strings
df['title'] = df['title'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)
df['summary'] = df['summary'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['link'] = df['link'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)
df['category'] = df['category'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)
df['author'] = df['author'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)
df['score'] = df['score'].replace('', np.nan)  # Replace empty strings with NaN
df['score'] = pd.to_numeric(df['score'], errors='coerce').fillna(0)  # Fill NaN with 0
df['id'] = pd.to_numeric(df['id'], errors='coerce')

# Combine text fields
df['texto'] = df['title'] + ' ' + df['summary']

df = df.drop_duplicates(subset='texto')

df_copia = df

"""### Creação do Embedding"""

def compile_text(x):
    text =  f"""post_categories: {x['category']},
                entry_title: {x['title']},
                link_news: {x['link']},
                content_title: {x['summary']},
                date: {x['date']},
                text: {x['texto']},
                score: {x['score']},
                author: {x['author']},
            """
    return text

# Generate sentences and keep references
sentences = df.apply(lambda x: compile_text(x), axis=1).tolist()
titles = df['title'].tolist()  # or use a unique ID if available

# Generate embeddings
model = SentenceTransformer("sentence-transformers/paraphrase-MiniLM-L6-v2")
# Generate embeddings (numerical only)
embeddings = model.encode(sentences=sentences, show_progress_bar=True, normalize_embeddings=True)
df_embedding = pd.DataFrame(embeddings)

# Save numerical embeddings ONLY
df_embedding.to_csv("embedding_train.csv", index=False)

# OPTIONAL: Save titles/metadata separately
df[['title', 'texto']].to_csv("metadata_train.csv", index=False)

"""### Funções uteis"""

def get_pca_2d(df, predict):

    pca_2d_object = prince.PCA(
    n_components=2,
    n_iter=3,
    rescale_with_mean=True,
    rescale_with_std=True,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42
    )

    pca_2d_object.fit(df)

    df_pca_2d = pca_2d_object.transform(df)
    df_pca_2d.columns = ["comp1", "comp2"]
    df_pca_2d["cluster"] = predict

    return pca_2d_object, df_pca_2d



def get_pca_3d(df, predict):

    pca_3d_object = prince.PCA(
    n_components=3,
    n_iter=3,
    rescale_with_mean=True,
    rescale_with_std=True,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42
    )

    pca_3d_object.fit(df)

    df_pca_3d = pca_3d_object.transform(df)
    df_pca_3d.columns = ["comp1", "comp2", "comp3"]
    df_pca_3d["cluster"] = predict

    return pca_3d_object, df_pca_3d



def plot_pca_3d(df, title="PCA Space", opacity=0.8, width_line=0.1):
    df = df.astype({"cluster": "object"})
    df = df.sort_values("cluster")

    fig = px.scatter_3d(
        df,
        x='comp1',
        y='comp2',
        z='comp3',
        color='cluster',
        title=title
    ).update_traces(
        marker={
            "size": 4,
            "opacity": opacity,
            "line": {
                "width": width_line,
                "color": "black",
            }
        }
    ).update_layout(
        scene=dict(
            xaxis=dict(
                title='Component 1',
                title_font=dict(color='black')  # Note the underscore
            ),
            yaxis=dict(
                title='Component 2',
                title_font=dict(color='black')  # Note the underscore
            ),
            zaxis=dict(
                title='Component 3',
                title_font=dict(color='black')  # Note the underscore
            )
        )
    )
    fig.show()


def plot_pca_2d(df, title="PCA Space", opacity=1, width_line=0.1):
    df = df.astype({"cluster": "object"})
    fig = px.scatter(
        df,
        x='comp1',
        y='comp2',
        color='cluster',
        title=title
    ).update_traces(
        marker={
            "size": 4,
            "opacity": opacity,
            "line": {
                "width": width_line,
                "color": "black",
            }
        }
    ).update_layout(
        xaxis_title='Component 1',
        yaxis_title='Component 2',
        xaxis=dict(title_font=dict(color='black')),
        yaxis=dict(title_font=dict(color='black'))
    )
    fig.show()
    
"""### Outliers"""

clf = ECOD()
clf.fit(df_embedding)


out = clf.predict(df_embedding)
df_embedding["outliers"] = out
df["outliers"] = out

df_embedding_no_out = df_embedding[df_embedding["outliers"] == 0]
df_embedding_no_out = df_embedding_no_out.drop(["outliers"], axis = 1)


df_embedding_with_out = df_embedding.copy()
df_embedding_with_out = df_embedding_with_out.drop(["outliers"], axis = 1)

df_embedding_no_out.shape

df_embedding_with_out.shape

km = KMeans(init="k-means++", random_state=0, n_init="auto")
visualizer = KElbowVisualizer(km, k=(2,10), locate_elbow=False)

visualizer.fit(df_embedding_with_out)        # Fit the data to the visualizer
visualizer.show()

"""### Best Number of Cluster"""

def make_Silhouette_plot(X, n_clusters):
     plt.xlim([-0.1, 1])
     plt.ylim([0, len(X) + (n_clusters + 1) * 10])
     clusterer = KMeans(n_clusters=n_clusters, max_iter = 1000, n_init = 10, init = 'k-means++', random_state=10)
     cluster_labels = clusterer.fit_predict(X)
     silhouette_avg = silhouette_score(X, cluster_labels)
     print(
         "For n_clusters =", n_clusters,
         "The average silhouette_score is :", silhouette_avg,
     )
 # Compute the silhouette scores for each sample
     sample_silhouette_values = silhouette_samples(X, cluster_labels)
     y_lower = 10
     for i in range(n_clusters):
         ith_cluster_silhouette_values = sample_silhouette_values[cluster_labels == i]
         ith_cluster_silhouette_values.sort()
         size_cluster_i = ith_cluster_silhouette_values.shape[0]
         y_upper = y_lower + size_cluster_i
         color = cm.nipy_spectral(float(i) / n_clusters)
         plt.fill_betweenx(
             np.arange(y_lower, y_upper),
             0,
             ith_cluster_silhouette_values,
             facecolor=color,
             edgecolor=color,
             alpha=0.7,
         )
         plt.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))
         y_lower = y_upper + 10
         plt.title(f"The Silhouette Plot for n_cluster = {n_clusters}", fontsize=26)
         plt.xlabel("The silhouette coefficient values", fontsize=24)
         plt.ylabel("Cluster label", fontsize=24)
         plt.axvline(x=silhouette_avg, color="red", linestyle="--")
         plt.yticks([])
         plt.xticks([-0.1, 0, 0.2, 0.4, 0.6, 0.8, 1])

range_n_clusters = list(range(2,10))
for n_clusters in range_n_clusters:
     print(f"N cluster: {n_clusters}")
     make_Silhouette_plot(df_embedding_no_out, n_clusters)
     plt.savefig('Silhouette_plot_{}.png'.format(n_clusters))
     plt.close()


"""### Modeling"""

n_clusters = 5

clusters = KMeans(n_clusters=n_clusters, init = "k-means++").fit(df_embedding_no_out)
print(clusters.inertia_)
clusters_predict = clusters.predict(df_embedding_no_out)

clusters_predict

"""### Evaluation"""

from sklearn.metrics import silhouette_score
from sklearn.metrics import calinski_harabasz_score
from sklearn.metrics import davies_bouldin_score

"""
The Davies Bouldin index is defined as the average similarity measure of each cluster with its most similar cluster, where similarity is the ratio of within-cluster distances to between-cluster distances.
The minimum value of the DB Index is 0, whereas a smaller value (closer to 0) represents a better model that produces better clusters.
"""
print(f"Davies bouldin score: {davies_bouldin_score(df_embedding_no_out,clusters_predict)}")

"""
Calinski Harabaz Index -> Variance Ratio Criterion.
Calinski Harabaz Index is defined as the ratio of the sum of between-cluster dispersion and of within-cluster dispersion.
The higher the index the more separable the clusters.
"""
print(f"Calinski Score: {calinski_harabasz_score(df_embedding_no_out,clusters_predict)}")


"""
The silhouette score is a metric used to calculate the goodness of fit of a clustering algorithm, but can also be used as a method for determining an optimal value of k (see here for more).
Its value ranges from -1 to 1.
A value of 0 indicates clusters are overlapping and either the data or the value of k is incorrect.
1 is the ideal value and indicates that clusters are very dense and nicely separated.
"""
print(f"Silhouette Score: {silhouette_score(df_embedding_no_out,clusters_predict)}")

pca_3d_object, df_pca_3d = get_pca_3d(df_embedding_no_out, clusters_predict)
plot_pca_3d(df_pca_3d, title = "PCA Space", opacity=1, width_line = 0.1)
print("The variability is :", pca_3d_object.eigenvalues_summary)

pca_2d_object, df_pca_2d = get_pca_2d(df_embedding_no_out, clusters_predict)
plot_pca_2d(df_pca_2d, title = "PCA Space", opacity=1, width_line = 0.2)

"""#### t-SNE 3D"""

sampling_data = df_embedding_no_out.sample(frac=0.5, replace=True, random_state=1)
sampling_clusters = pd.DataFrame(clusters_predict).sample(frac=0.5, replace=True, random_state=1)[0].values

df_tsne_3d = TSNE(
                  n_components=3,
                  learning_rate=500,
                  init='random',
                  perplexity=200,
                  n_iter = 5000).fit_transform(sampling_data)

df_tsne_3d = pd.DataFrame(df_tsne_3d, columns=["comp1", "comp2",'comp3'])
df_tsne_3d["cluster"] = sampling_clusters
plot_pca_3d(df_tsne_3d, title = "T-SNE Space", opacity=1, width_line = 0.1)

plot_pca_3d(df_tsne_3d, title = "T-SNE Space", opacity=0.1, width_line = 0.1)

"""#### t-SNE 2D"""

df_tsne_2d = TSNE(
                  n_components=2,
                  learning_rate=500,
                  init='random',
                  perplexity=200,
                  n_iter = 5000).fit_transform(sampling_data)

df_tsne_2d = pd.DataFrame(df_tsne_2d, columns=["comp1", "comp2"])
df_tsne_2d["cluster"] = sampling_clusters

plot_pca_2d(df_tsne_2d, title = "PCA Space", opacity=0.5, width_line = 0.5)

df_tsne_2d.head()

plot_pca_2d(df_tsne_2d, title = "PCA Space", opacity=1, width_line = 0.5)

"""## Explanations"""

def get_top_5_closest_to_centroid(df_pca_3d, original_df, cluster_column="cluster", n_closest=5):
    """
    Retorna as N ideias mais próximas do centróide de cada cluster.

    Args:
        df_pca_3d (pandas.DataFrame): DataFrame contendo as componentes principais e os clusters.
        original_df (pandas.DataFrame): DataFrame original contendo as informações das ideias.
        cluster_column (str): Nome da coluna que identifica os clusters.
        n_closest (int): Número de ideias mais próximas do centróide a serem retornadas.

    Returns:
        dict: Dicionário onde as chaves são os clusters e os valores são DataFrames com as N ideias mais próximas.
    """
    resultados = {}

    # Certificar-se de que os índices estão alinhados
    original_df = original_df.reset_index(drop=True)
    df_pca_3d = df_pca_3d.reset_index(drop=True)

    # Iterar sobre os clusters únicos
    for cluster in df_pca_3d[cluster_column].unique():
        # Filtrar o DataFrame pelo cluster atual
        df_cluster = df_pca_3d[df_pca_3d[cluster_column] == cluster]

        # Calcular o centróide do cluster
        centroid = df_cluster[["comp1", "comp2", "comp3"]].mean().values

        # Calcular a distância de cada ponto ao centróide
        df_cluster = df_cluster.copy()  # Evitar SettingWithCopyWarning
        df_cluster["distance_to_centroid"] = df_cluster.apply(
            lambda row: np.linalg.norm(row[["comp1", "comp2", "comp3"]].values - centroid),
            axis=1
        )

        # Selecionar as N ideias mais próximas
        closest_points = df_cluster.nsmallest(n_closest, "distance_to_centroid")

        # Recuperar as informações correspondentes do DataFrame original
        closest_ideas = original_df.loc[closest_points.index]

        # Salvar no dicionário
        resultados[cluster] = closest_ideas

    return resultados

# Chama a função para obter as 5 ideias mais próximas do centróide de cada cluster
# Resetar os índices para alinhar os dados antes de rodar o KMeans
# Reset indices to avoid KeyError
df_embedding_no_out = df_embedding_no_out.reset_index(drop=True)
df_copia = df_copia.reset_index(drop=True)

# Align DataFrames
df_copia_alinhado = df_copia.loc[df_embedding_no_out.index].reset_index(drop=True)

# Add clusters to the aligned DataFrame
if len(df_copia_alinhado) == len(clusters_predict):
    df_copia_alinhado['cluster'] = clusters_predict
else:
    raise ValueError(f"Length mismatch: df_copia_alinhado ({len(df_copia_alinhado)}) vs clusters_predict ({len(clusters_predict)})")
print(df_copia_alinhado.head())  # Check available columns

top_5_ideas_per_cluster = get_top_5_closest_to_centroid(df_pca_3d, df_copia_alinhado)

# Itera sobre o dicionário retornado pela função
for cluster, ideas in top_5_ideas_per_cluster.items():
    print(f"Cluster {cluster}:")
    print(ideas)  # Exibe o DataFrame com as N ideias mais próximas
    print("\n")  # Adiciona uma linha em branco entre os clusters

def plot_clusters_with_distances_and_centroids_hover(df_pca_3d, top_5_ideas_per_cluster, title="Top 5 Closest Ideas"):
    """
    Plota um gráfico 3D exibindo as 5 ideias mais próximas ao centróide de cada cluster,
    com linhas conectando os pontos aos seus respectivos centróides, e as distâncias entre eles.
    """
    # DataFrame consolidado para pontos mais próximos
    closest_points_df = pd.DataFrame()
    centroids = []

    # Definir manualmente as cores dos clusters
    cluster_colors = {
        0: 'lightpink',
        1: 'lightblue',
        2: 'greenyellow',
        3: 'rebeccapurple',
        4: 'goldenrod',
    }

    # Ordenar os clusters
    cluster_order = sorted(cluster_colors.keys())
    sorted_cluster_colors = {cluster: cluster_colors[cluster] for cluster in cluster_order}

    # Mapear a cor dos clusters
    df_pca_3d['color'] = df_pca_3d['cluster'].map(sorted_cluster_colors)

    for cluster, closest_points in top_5_ideas_per_cluster.items():
        valid_indices = closest_points.index.intersection(df_pca_3d.index)
        
        if len(valid_indices) > 0:
            df_cluster = df_pca_3d[df_pca_3d['cluster'] == cluster]
            centroid = df_cluster[['comp1', 'comp2', 'comp3']].mean().values

            distances = np.linalg.norm(df_pca_3d.loc[valid_indices][['comp1', 'comp2', 'comp3']].values - centroid, axis=1)
            closest_points_df_cluster = df_pca_3d.loc[valid_indices].iloc[np.argsort(distances)][:5]
            closest_points_df = pd.concat([closest_points_df, closest_points_df_cluster])

            centroids.append({
                'cluster': cluster,
                'comp1': centroid[0],
                'comp2': centroid[1],
                'comp3': centroid[2],
                'color': sorted_cluster_colors.get(cluster, 'gray')
            })

    if closest_points_df.empty:
        raise ValueError("Nenhum ponto válido foi encontrado para plotar.")

    closest_points_df = closest_points_df.astype({"cluster": "object"})

    # Garantir que a coluna 'title' existe
    if 'title' not in closest_points_df.columns:
        if 'title' in df_copia_alinhado.columns:
            closest_points_df = closest_points_df.copy()
            closest_points_df['title'] = df_copia_alinhado.loc[closest_points_df.index, 'title'].values
        else:
            closest_points_df['title'] = closest_points_df.index.astype(str)

    # Criar figura com configurações corretas
    fig = px.scatter_3d(
        closest_points_df,
        x='comp1',
        y='comp2',
        z='comp3',
        color='cluster',
        text=closest_points_df.index,
        hover_name='title',
        template="plotly",
        color_discrete_map=sorted_cluster_colors,
        title=title
    ).update_traces(
        marker={
            "size": 8,
            "opacity": 0.8,
            "line": {"width": 1.5, "color": "black"}
        },
        textposition="top center",
    )

    # Configuração correta do layout
    fig.update_layout(
        width=1000,
        height=800,
        autosize=False,
        showlegend=True,
        legend=dict(
            title_font_family="Times New Roman",
            font=dict(size=20)
        ),
        scene=dict(
            xaxis=dict(title='comp1', title_font=dict(color='black')),
            yaxis=dict(title='comp2', title_font=dict(color='black')),
            zaxis=dict(title='comp3', title_font=dict(color='black'))
        ),
        font=dict(
            family="Gilroy",
            color='black',
            size=15
        )
    )
    # Adicionar centróides e linhas
    for centroid in centroids:
        fig.add_trace(
            go.Scatter3d(
                x=[centroid['comp1']],
                y=[centroid['comp2']],
                z=[centroid['comp3']],
                mode='markers+text',
                marker=dict(size=6, color=centroid['color'], symbol='x'),
                text=[f"Centroid {centroid['cluster']}"],
                textposition='bottom center',
                name=f"Centroid {centroid['cluster']}"
            )
        )

        for _, point in closest_points_df[closest_points_df['cluster'] == centroid['cluster']].iterrows():
            x_coords = [point['comp1'], centroid['comp1']]
            y_coords = [point['comp2'], centroid['comp2']]
            z_coords = [point['comp3'], centroid['comp3']]
            
            distance = np.linalg.norm([
                point['comp1'] - centroid['comp1'],
                point['comp2'] - centroid['comp2'],
                point['comp3'] - centroid['comp3']
            ])
            
            midpoint_x = (point['comp1'] + centroid['comp1']) / 2
            midpoint_y = (point['comp2'] + centroid['comp2']) / 2
            midpoint_z = (point['comp3'] + centroid['comp3']) / 2
            
            fig.add_trace(go.Scatter3d(
                x=x_coords,
                y=y_coords,
                z=z_coords,
                mode='lines',
                line=dict(color=centroid['color'], width=2),
                showlegend=False
            ))
            
            fig.add_trace(go.Scatter3d(
                x=[midpoint_x],
                y=[midpoint_y],
                z=[midpoint_z],
                mode='text',
                text=[f"{distance:.2f}"],
                textposition="middle center",
                showlegend=False
            ))

    fig.show()


plot_clusters_with_distances_and_centroids_hover(df_pca_3d, top_5_ideas_per_cluster, title="Top 5 Closest Ideas to Centroid")

# Plotando os clusters com as 5 ideias mais próximas ao centróide
"""# busca semantica"""

df_copia = df_copia.reset_index(drop=True)

# Função para realizar a busca semântica
def busca_semantica(query):
    # Gera as embeddings para a query
    query_embedding = model.encode(query, convert_to_tensor=True)

    # Gera as embeddings para os textos (título e conteúdo)
    text_embeddings = model.encode(df_copia['texto'].tolist(), convert_to_tensor=True)

    # Calcula a similaridade coseno entre a query e os textos
    cosine_scores = util.pytorch_cos_sim(query_embedding, text_embeddings)[0]

    # Obtém o número máximo de resultados que podemos retornar
    num_results = min(10, len(cosine_scores))  # Ajusta para não exceder o número de entradas

    # Obtém os índices das melhores correspondências
    top_results = np.argpartition(-cosine_scores.numpy(), range(num_results))[:num_results]

    # Ordena os resultados para obter os scores mais altos
    top_results = top_results[np.argsort(-cosine_scores.numpy()[top_results])]

    resultados = []
    print("\nTop resultados para a consulta:", query)
    for idx in top_results:
        resultado = {
            'score': cosine_scores[idx].item(),  # Converte tensor para valor numérico
            'titulo': df['title'].iloc[idx],
            'texto': df['summary'].iloc[idx],
            'link': df['link'].iloc[idx]
        }
        resultados.append(resultado)

    return resultados  # Retorna a lista de resultados

# Exemplo de uso
queries = ["Smartwatch", "green energy", "trend clothes", "papyrus paper"]
resultados = {}

for query in queries:
    resultados[query] = busca_semantica(query)

# Agora você pode acessar os resultados
#for resultado in resultados:
#    print(f"Score: {resultado['score']:.4f} | Título: {resultado['titulo']} | Texto: {resultado['texto']} | Link: {resultado['link']}\n")

from sklearn.metrics.pairwise import cosine_similarity


def calcular_similaridade_por_categoria(df):
    """
    Calcula a similaridade de cossenos entre os textos de cada categoria.

    Args:
        df (pd.DataFrame): DataFrame contendo as colunas ['category', 'title', ...].

    Returns:
        dict: Dicionário com as categorias como chave e listas de pares de textos similares e suas similaridades.
    """
    resultados = {}

    # Iterar sobre cada categoria
    for categoria, grupo in df.groupby('category'):
        print(f"Processando categoria: {categoria}")

        # Compilar textos para a categoria atual
        sentences = grupo.apply(lambda x: compile_text(x), axis=1).tolist()

        # Calcular os embeddings
        model = SentenceTransformer(r"sentence-transformers/paraphrase-MiniLM-L6-v2")
        embeddings = model.encode(sentences, normalize_embeddings=True)

        # Similaridades de cossenos
        sim_matrix = cosine_similarity(embeddings)

        # Encontrar os pares mais similares
        pares_similares = []
        for i in range(len(sentences)):
            for j in range(i + 1, len(sentences)):
                pares_similares.append((i, j, sim_matrix[i][j]))

        # Ordenar os pares pela similaridade
        pares_similares = sorted(pares_similares, key=lambda x: x[2], reverse=True)

        # Adicionar resultados ao dicionário
        resultados[categoria] = [
            {
                'Texto 1': sentences[i],
                'Texto 2': sentences[j],
                'Similaridade': sim
            }
            for i, j, sim in pares_similares
        ]

    return resultados

# Uso da função
df['compiled_text'] = df.apply(lambda x: compile_text(x), axis=1)

# Calculando os pares mais similares para cada categoria
resultados_por_categoria = calcular_similaridade_por_categoria(df)

# Exemplo de exibição dos resultados de uma categoria
categoria_exemplo = list(resultados_por_categoria.keys())[0]
print(f"Categoria: {categoria_exemplo}\n")
for resultado in resultados_por_categoria[categoria_exemplo][:5]:  # Mostra os 5 primeiros
    print(resultado)

"""# Grafo e numero de palavras por query escolhida"""

import networkx as nx
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re

def criar_grafo(query, resultados):
    """
    Cria um grafo com a palavra pai no centro e títulos conectados com scores.

    Args:
        palavra_pai (str): A palavra central do grafo.
        lista_dados (list): Lista de dicionários com dados de títulos, scores, textos e links.

    Returns:
        G (networkx.Graph): Grafo criado.
    """
    G = nx.Graph()
    G.add_node(query, tamanho=len(query))  # Adiciona a palavra pai como nó central

    # Adiciona os títulos como nós e conecta à palavra pai com o score
    for item in resultados:
        titulo = item['titulo']
        score = item['score']
        G.add_node(titulo, texto=item['texto'], link=item['link'], tamanho=len(titulo))  # Adiciona nó com atributos
        G.add_edge(query, titulo, score=score)  # Conecta ao nó central

    return G

def desenhar_grafo(G, query):
    """
    Desenha o grafo com círculos transparentes para esconder as arestas, mantendo o texto visível.

    Args:
        G (networkx.Graph): O grafo a ser desenhado.
        query (str): A palavra central do grafo.
    """
    pos = nx.spring_layout(G)  # Layout para posicionar os nós
    plt.figure(figsize=(12, 8))

    # Tamanhos dos círculos proporcionais ao comprimento do texto (multiplicador para escala maior)
    fator_escala = 150  # Ajuste para círculos maiores
    tamanhos = [G.nodes[node]['tamanho'] * fator_escala for node in G.nodes]

    # Desenha os nós com transparência
    nx.draw_networkx_nodes(
        G, pos, node_color="lightblue", node_size=tamanhos, alpha=0.3
    )

    # Desenha as arestas
    nx.draw_networkx_edges(G, pos, width=1.5, alpha=0.7, edge_color="gray")

    # Adiciona rótulos aos nós
    node_labels = {node: node for node in G.nodes}
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=10)

    # Adiciona rótulos às arestas (scores)
    edge_labels = {(u, v): f"{d['score']:.2f}" for u, v, d in G.edges(data=True)}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color="red")

    # Título geral
    plt.title(f"Grafo para '{query}'", fontsize=16)
    plt.axis("off")
    plt.show()

def gerar_nuvem_de_palavras(resultados):
    """
    Gera uma nuvem de palavras com base nos textos associados aos itens da lista.

    Args:
        resultados (list): Lista de dicionários com os textos.

    """
    # Coleta todos os textos da lista
    todos_textos = " ".join(item['texto'] for item in resultados)

    # Limpeza básica e tokenização
    palavras = re.findall(r'\b\w+\b', todos_textos.lower())
    palavras_filtradas = [p for p in palavras if len(p) > 3]  # Filtra palavras com mais de 3 letras

    # Cria a nuvem de palavras
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(" ".join(palavras_filtradas))

    # Exibe a nuvem
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.axis("off")
    plt.title("Nuvem de Palavras", fontsize=16)
    plt.show()

for query, lista_resultados in resultados.items():
    # Criação do grafo
    G = criar_grafo(query, lista_resultados)
    # Desenha o grafo
    desenhar_grafo(G, query)
    # Gera a nuvem de palavras
    gerar_nuvem_de_palavras(lista_resultados)





"""# Nuvem de palavras por categoria"""

def gerar_nuvem_por_categoria(df):
    """
    Gera uma nuvem de palavras para cada categoria de post no DataFrame.

    Args:
        df (pandas.DataFrame): DataFrame com as colunas ['category', 'summary', 'texto'].
    """
    categorias = df['category'].unique()  # Identifica as categorias únicas

    for categoria in categorias:
        # Filtra os posts da categoria
        categoria_df = df[df['category'] == categoria]

        # Coleta todos os textos da categoria (usando 'summary' ou 'texto')
        todos_textos = " ".join(categoria_df['summary'].dropna())

        # Limpeza básica e tokenização
        palavras = re.findall(r'\b\w+\b', todos_textos.lower())
        palavras_filtradas = [p for p in palavras if len(p) > 3]  # Filtra palavras com mais de 3 letras

        # Só gera a nuvem se houver palavras suficientes
        if palavras_filtradas:
            wordcloud = WordCloud(width=800, height=400, background_color='white').generate(" ".join(palavras_filtradas))

            # Exibe a nuvem
            plt.figure(figsize=(10, 5))
            plt.imshow(wordcloud, interpolation="bilinear")
            plt.axis("off")
            plt.title(f"Nuvem de Palavras - Categoria: {categoria}", fontsize=16)
            plt.show()
        else:
            print(f"Categoria '{categoria}' não possui palavras suficientes para gerar uma nuvem de palavras.")

gerar_nuvem_por_categoria(df)

"""# Analise das categorias"""

import matplotlib.pyplot as plt
import seaborn as sns

def gerar_grafico_dunnets(df):
    """
    Gera um gráfico de Dunnets (barra) mostrando quantos posts existem por categoria em 'category'.

    Args:
        df (pandas.DataFrame): DataFrame com a coluna 'category'.
    """
    # Conta quantos posts existem para cada categoria
    contagem_categorias = df['category'].value_counts().sort_values(ascending=False)

    # Criação do gráfico
    plt.figure(figsize=(10, 6))
    sns.barplot(x=contagem_categorias.index, y=contagem_categorias.values, palette='viridis')

    # Adicionando título e rótulos
    plt.title('Número de Posts por Categoria', fontsize=16)
    plt.xlabel('Categorias de Posts', fontsize=12)
    plt.ylabel('Número de Posts', fontsize=12)
    plt.xticks(rotation=45, ha='right')  # Rotaciona os rótulos das categorias para melhor visualização
    plt.tight_layout()

    # Exibe o gráfico
    plt.show()

# df.head()  # Removido para evitar execução desnecessária

gerar_grafico_dunnets(df)

"""# Quantidades de entradas de post"""

def gerar_grafico_quantidade_por_ano_mes(df):
    """
    Gera um gráfico de colunas mostrando as 10 maiores quantidades de posts por ano e mês,
    bem como as 10 maiores quantidades de posts por mês-ano, independentemente do ano.

    Args:
        df (pandas.DataFrame): DataFrame com a coluna 'date' (data no formato ano-mês-dia).
    """
    # Converte a coluna 'date' para o formato datetime
    df['date'] = pd.to_datetime(df['date'], errors='coerce')

    # Extrai o ano e o mês da data
    df['ano_mes'] = df['date'].dt.to_period('M')  # Ano-Mês como period
    df['ano'] = df['date'].dt.year  # Extrai o ano

    # Conta a quantidade de posts por ano-mês
    contagem_ano_mes = df['ano_mes'].value_counts().sort_values(ascending=False)

    # Seleciona as 10 maiores quantidades de posts por ano-mês
    top_10_ano_mes = contagem_ano_mes.head(10)

    # Criação de subplots para mostrar os gráficos lado a lado
    _, axs = plt.subplots(1, 2, figsize=(14, 6))
    # Gráfico de barras para o top 10 por ano
    contagem_ano = df['ano'].value_counts().sort_values(ascending=False)
    top_10_ano = contagem_ano.head(10)

    top_10_ano.plot(kind='bar', color='skyblue', ax=axs[0])
    axs[0].set_title('Top 10 Quantidade de Posts por Ano', fontsize=14)
    axs[0].set_xlabel('Ano', fontsize=12)
    axs[0].set_ylabel('Número de Posts', fontsize=12)
    axs[0].tick_params(axis='x', rotation=45)

    # Gráfico de barras para o top 10 por ano-mês
    top_10_ano_mes.plot(kind='bar', color='lightcoral', ax=axs[1])
    axs[1].set_title('Top 10 Quantidade de Posts por Ano-Mês', fontsize=14)
    axs[1].set_xlabel('Ano-Mês', fontsize=12)
    axs[1].set_ylabel('Número de Posts', fontsize=12)
    axs[1].tick_params(axis='x', rotation=45)

    # Ajustando layout para não sobrepor os gráficos
    plt.tight_layout()

    # Exibe os gráficos
    plt.show()

gerar_grafico_quantidade_por_ano_mes(df)

df_embedding_no_out.head()

# Resetar os índices para alinhar os dados antes de rodar o KMeans
df_copia_alinhado = df_copia.loc[df_embedding_no_out.index].reset_index(drop=True)

# Certifique-se de que os tamanhos estão alinhados
print(f"Tamanho do DataFrame alinhado: {len(df_copia_alinhado)}")
print(f"Tamanho dos embeddings: {len(clusters_predict)}")

# Adicionar os clusters ao DataFrame alinhado
df_copia_alinhado['cluster'] = clusters_predict
#df_copia_alinhado['peso_ate_centroide'] =
# Exibir um exemplo do DataFrame com os clusters adicionados

df_copia_alinhado.head(10)

df_copia_alinhado.columns

import re
from nltk.corpus import stopwords
import nltk

# Baixar as stopwords da biblioteca nltk
nltk.download('stopwords')
stopwords_nltk = set(stopwords.words('english'))  # Ajuste o idioma conforme necessário, por exemplo, 'portuguese'

def limpar_texto(texto, stopwords, min_caracteres=3):
    """
    Remove palavras ruído de um texto.

    Args:
        texto (str): Texto original.
        stopwords (set): Conjunto de palavras a serem removidas.
        min_caracteres (int): Número mínimo de caracteres para manter uma palavra.

    Returns:
        str: Texto limpo.
    """
    if not isinstance(texto, str):
        return ""  # Retorna vazio se o texto não for uma string

    # Remove caracteres especiais, números e transforma em minúsculas
    texto = re.sub(r"[^\w\s]", "", texto).lower()

    # Filtra as palavras removendo as que estão em stopwords ou têm poucos caracteres
    palavras = texto.split()
    palavras_filtradas = [
        palavra for palavra in palavras
        if palavra not in stopwords and len(palavra) >= min_caracteres
    ]

    return " ".join(palavras_filtradas)

def gerar_nuvem_palavras_por_cluster(df, min_caracteres=3):
    """
    Gera e exibe uma nuvem de palavras para cada cluster no DataFrame.

    Args:
        df (pandas.DataFrame): DataFrame contendo as colunas 'texto' e 'cluster'.
        min_caracteres (int): Número mínimo de caracteres para manter uma palavra.
    """
    # Verifica se as colunas necessárias existem
    if 'texto' not in df.columns or 'cluster' not in df.columns:
        print("O DataFrame deve conter as colunas 'texto' e 'cluster'.")
        return

    clusters_unicos = df['cluster'].dropna().unique()
    for cluster in clusters_unicos:
        # Filtrar o DataFrame para o cluster atual e remover NaN
        textos_cluster = df[df['cluster'] == cluster]['texto'].dropna()

        # Manter apenas os valores que são strings e limpar o texto
        textos_filtrados = textos_cluster[textos_cluster.apply(lambda x: isinstance(x, str))]
        textos_limpos = textos_filtrados.apply(lambda x: limpar_texto(x, stopwords_nltk, min_caracteres))

        # Concatenar todos os textos do cluster
        texto_unico = " ".join(textos_limpos)

        # Verificar se há texto para gerar a nuvem
        if texto_unico.strip():
            # Gerar a nuvem de palavras
            wordcloud = WordCloud(
                width=800,
                height=400,
                background_color='white',
                max_words=200,
                contour_width=3,
                contour_color='steelblue',
                collocations=False
            ).generate(texto_unico)

            # Mostrar a nuvem de palavras
            plt.figure(figsize=(10, 5))
            plt.imshow(wordcloud, interpolation='bilinear')
            plt.axis('off')
            plt.title(f"Nuvem de Palavras para o Cluster {cluster}", fontsize=16)
            plt.show()
        else:
            print(f"Cluster {cluster} não possui textos válidos para gerar uma nuvem.")

# Chamar a função com o DataFrame 'df_copia_alinhado'
gerar_nuvem_palavras_por_cluster(df_copia_alinhado)

def gerar_graficos_post_categories_por_cluster(df):
    """
    Gera gráficos de barras para os top 5 category de cada cluster.

    Args:
        df (pandas.DataFrame): DataFrame contendo as colunas 'category' e 'cluster'.
    """
    # Verifica se as colunas necessárias existem
    if 'category' not in df.columns or 'cluster' not in df.columns:
        print("O DataFrame deve conter as colunas 'category' e 'cluster'.")
        return

    clusters_unicos = df['cluster'].dropna().unique()

    for cluster in clusters_unicos:
        # Filtrar o DataFrame para o cluster atual
        df_cluster = df[df['cluster'] == cluster]

        # Contar a frequência de cada categoria no cluster
        categorias_contagem = df_cluster['category'].value_counts()

        # Selecionar as top 5 categorias
        top_categorias = categorias_contagem.head(5)

        # Verificar se há categorias suficientes para gerar o gráfico
        if not top_categorias.empty:
            # Criar o gráfico de barras
            plt.figure(figsize=(8, 5))
            top_categorias.plot(kind='bar', color='skyblue')

            # Adicionar título e rótulos
            plt.title(f"Top 5 Post-Categories no Cluster {cluster}", fontsize=16)
            plt.xlabel("Post-Categories", fontsize=12)
            plt.ylabel("Número de Posts", fontsize=12)
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()

            # Exibir o gráfico
            plt.show()
        else:
            print(f"Cluster {cluster} não possui categorias suficientes para gerar um gráfico.")

# Chamar a função com o DataFrame 'df_copia_alinhado'
gerar_graficos_post_categories_por_cluster(df_copia_alinhado)

